name: Testing Workflow

on: push 

jobs:
    test-job:
        runs-on: ubuntu-latest 

        steps: 
            - name: Hello display
              run: echo "Hello ms group"

            - name: Display the date
              run: date 
